{% set version = "1.7.1" %}


package:
    name: django-redis-cache
    version: {{ version }}

source:
    fn: django-redis-cache-{{ version }}.tar.gz
    url: https://pypi.python.org/packages/e9/50/13d72d9d3a3c8ffd3c66dc91f2918f9f6bc8454c3d869dd86576e2e02aaa/django-redis-cache-1.7.1.tar.gz
    md5: 741907c4e36923601827ad06d9ba7bf1

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt
    skip: True  # [win]

requirements:
    build:
        - python
        - django
        - setuptools
        - redis-py >=2.10.3
    run:
        - python
        - django
        - redis-py >=2.10.3

test:
    imports:
        - redis_cache

about:
    home: http://github.com/sebleier/django-redis-cache/
    license: BSD-3 clause
    summary: Redis Cache Backend for Django

extra:
    recipe-maintainers:
        - kwilcox
