{% set version = "2.1.0" %}

package:
  name: django-redis-cache
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-redis-cache/django-redis-cache-{{ version }}.tar.gz
  sha256: 5c581743de5994e6b15abfd5b3dbcb8bf00e42d97658c96b7218bcb6a63f863b

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - django
    - redis <4.0
    - six

test:
  imports:
    - redis_cache

about:
  home: http://github.com/sebleier/django-redis-cache/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'Redis Cache Backend for Django'

extra:
  recipe-maintainers:
    - kwilcox
